### ISSUE TITLE
Incorrect axis name in dqc_15_exclusion_rules.csv

### ISSUE THREAD

**Issue by maneesh-xc** [DataQualityCommittee/dqc_us_rules#13]
It should be dei:LegalEntityAxis instead of us-gaap:LegalEntityAxis in last 4 lines of [dqc_15_exclusion_rules.csv](https://github.com/DataQualityCommittee/dqc_us_rules/blob/master/src/resources/DQC_US_0015/dqc_15_exclusion_rules.csv). This is causing test case id DQC_0015.1367.2608 to fail (creates 5 errors when it should only create 3).

**Comment by hefischer** [comment]
Fixed 2015-12-07 with https://github.com/DataQualityCommittee/dqc_us_rules/commit/984a5a2152529cc2ff8992ae8bfe0826b5deecbb#diff-a241752ea142dd08f1dd7e0948d4f676
