### ISSUE TITLE
Arelle + DQC plugin error 

### ISSUE THREAD

**Issue by neilapwills** [DataQualityCommittee/dqc_us_rules#2]
Downloaded latest Arelle
Downloaded DQC python plugin
Manage plugin > dqc_us_rules-master\dqc_us_rules-master\src\__init__.py

screenshot
![image](https://cloud.githubusercontent.com/assets/13490426/8886345/70e00a96-321d-11e5-84c1-6c7fc32fee3d.png)

**Comment by neilapwills** [comment]
Windows 7 had an issue

Add-in works under Mac OSX

**Comment by hefischer** [comment]
I’ll test on Windows 7 & 10 when back from Vacation.

   Herm

**Comment by susanyount-wf** [comment]
We will prepare a binary build and send it to you.

**Comment by andrewperkins-wf** [comment]
The issue you ran into should be fixed on the latest master release @neilapwills .  I will close this, and you can reopen if you continue to see the issue.  Thanks!
