### ISSUE TITLE
Certain rules do not seem to be getting triggered

### ISSUE THREAD

**Issue by edimusrex** [DataQualityCommittee/dqc_us_rules#26]
We are running the current dqc_us_rules webservice to verify our xbrl packages but have noticed that the output from the service running at XBRLUS site does not match the output that we get on our own development server, more specifically if the rules are 4,6,9 or 36 they show up just fine but if they trigger rules 5,15 or 33 they do not appear at all.  We're not too sure what the issue is.  I have an example XBRL package I could send you for verification on your side.

Thank you

**Comment by campbellpryde** [comment]
Yes could you please send that to me thanks.

**Comment by edimusrex** [comment]
is there an email I can send it to?

**Comment by campbellpryde** [comment]
You can send to me at campbell.pryde@xbrl.us

Thank you

Campbell Pryde

President and CEO

(917) 582-6159


1211 Avenue of the Americas, 19th Floor

New York, NY 10036-8775


*xbrl.us* <http://xbrl.us/> is the national consortium

for xbrl business reporting standards

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate

**Comment by edimusrex** [comment]
I just received your message.  I will be available to call you after 11 pm today.

 

Thanks

 

Ed Dunn | Systems/Security Administrator

CompSci Resources, LLC
T: 703.750.3232
F: 703.750.3613

5520 Cherokee Avenue, Suite 230
Alexandria, VA 22312
www.compsciresources.com
 <http://www.compsciresources.com/> CompSciResources

**Comment by campbellpryde** [comment]
Thanks Ed can you call me at 11:00

Campbell Pryde

President and CEO

(917) 582-6159


1211 Avenue of the Americas, 19th Floor

New York, NY 10036-8775


*xbrl.us* <http://xbrl.us/> is the national consortium

for xbrl business reporting standards

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate

**Comment by edimusrex** [comment]
It seems like I have stumbled across my answer by accident.  Looks like were did not have the –disclosureSystem efm-pragmatic set on our webservice.  I am going to test this a little more and will give you a call if I am still running into any errors.

 

Thanks again

 

 

Ed Dunn | Systems/Security Administrator

CompSci Resources, LLC
T: 703.750.3232
F: 703.750.3613

5520 Cherokee Avenue, Suite 230
Alexandria, VA 22312
www.compsciresources.com
 <http://www.compsciresources.com/> CompSciResources

**Comment by andrewperkins-wf** [comment]
Yes, you have to have disclosure system set to an EFM disclosure system.  Sorry that was not clear.  It seems like this issue is resolved, so I will be closing it out.  Please feel free to reopen if this issue occurs again.
