### ISSUE TITLE
InterestCreditedToPolicyOwnerAccounts

### ISSUE THREAD

**Issue by deantp** [DataQualityCommittee/dqc_us_rules#37]
The adjustment required to reconcile net income to cash provided by (used in) operations related to the unpaid portion of interest credited to policy owner accounts.

**Comment by campbellpryde** [comment]
This element has a credit balance type in the US GAAP taxonomy when the item is an expense. Requesting that the FASB update this element to be a debit balance type.

**Comment by deantp** [comment]
Thanks, saw the comment go in.
