### ISSUE TITLE
InvestmentSoldNotYetPurchasedPercentOfNetAssets

### ISSUE THREAD

**Issue by deantp** [DataQualityCommittee/dqc_us_rules#38]
For schedules of investments sold, not yet purchased (short sales) that are categorized, each category would be expected to have a percent of net assets for the aggregated value of the investments sold short in the category.

**Comment by campbellpryde** [comment]
This element is not expected to have a negative value. If it is negative the filer would use InvestmentOwnedPercentOfNetAssets with a positive value.
