### ISSUE TITLE
PartnersCapitalAccountReturnOfCapital

### ISSUE THREAD

**Issue by deantp** [DataQualityCommittee/dqc_us_rules#41]
Change could be negative.

**Comment by campbellpryde** [comment]
Can you please provide an example of where this would be negative.  The instances from historical filing s where this has occurred have used this element even though it is not a return of capital to the partner.

**Comment by deantp** [comment]
https://www.sec.gov/Archives/edgar/data/1396446/000139644615000014/0001396446-15-000014-index.htm

SSE

**Comment by campbellpryde** [comment]
FYI the nonnegative rules are not active if a member from the components of shareholders equity is used. We are also adding the partners capital as an axis that exempts the rule from flagging if the line item is negative.
