### ISSUE TITLE
IFRS 2020 support

### ISSUE THREAD

**Issue by jonathan-lord-compsci** [DataQualityCommittee/dqc_us_rules#479]
Hi,

Could you please let me know when and where I would be able to find support for IFRS 2020? Thanks!

Best Regards,
Jonathan Lord

**Comment by davidtauriello** [comment]
Jonathan - we expect to add 2020 IFRS support to version 13 - public review starts August 1.

**Comment by jonathan-lord-compsci** [comment]
Dave, thanks for the heads up. I'll check in again in August.

**Comment by davidtauriello** [comment]
@jonathan-lord-compsci - I'm closing this issue; you'll find v13 **and** v12 include IFRS 2020 (added in the initial [v12.0.0](https://github.com/DataQualityCommittee/dqc_us_rules/releases) - sorry for the delay in updating here.
