### ISSUE TITLE
DQC_0033/variation.xml \ DQC_Testcases_v28\DQC_0033\variation.xml

### ISSUE THREAD

**Issue by neilapwills** [DataQualityCommittee/dqc_us_rules#5]
The primary item element is incorrect for each variation:

        <primaryElement>dei:DocumentType</primaryElement>

The expected results in the variation.xml file for this rule. All the variations for this test case list out dei:DocumentType as the violator, however on running the rule and also looking at the name and description of the variations, each of them have a different violator which is not the dei:DocumentType fact.

For example, the following variation:

<variation id="DQC_0033.2.22">
    <name>Context date of the element EntityFilerCategory is greater than the value of DocumentPeriodEndDate.</name>
    <description>Creates a fail case when the period end date on the context of the element EntityFilerCategory is greater than the value of the element DocumentPeriodEndDate</description>
    <data>
      <schema>DQC_0033.2/CASE_22/testco-20141231_22.xsd</schema>
      <instance readMeFirst="true">DQC_0033.2/CASE_22/testco-20141231_22.xml</instance>
    </data>
    <results blockedMessageCodes="DQC.US.0006.14">
      <error severity="error" count="1">DQC.US.0033.2</error>
      <result>
        <primaryElement>dei:DocumentType</primaryElement>
        <factValue>10-K</factValue>
        <startDate>2014-01-01</startDate>
        <endDate>2014-12-31</endDate>
        <dimensions />
        <message>The ending date of ${fact1.period.endDate} used for ${fact1.label} must be the same as the Document Period End Date, ${dei:DocumentPeriodEndDate.fact.period.endDate}. Revise either the date of the ${fact1.label} or the date of the Document Period End Date. \nThe properties of this ${fact1.name} fact are:\nPeriod: ${fact1.period}\nDimensions: ${fact1.dimensions}\nUnit: ${fact1.unit}\nRule version: ${ruleVersion}</message>
      </result>
    </results>
  </variation>

The name and the description says that EntityFilterCategory fact is the one that causes the error, which is correct when we looked at the instance documents. However, the result section mentions the details about the DocumentType fact. Other variations in the test case have similar problem which makes the test suite for DQC_0033 unusable.

We can make the changes and commit

**Comment by hefischer** [comment]
Neil,

I and I believe the others who could respond are on vacation this week, I’ll be available Mon night or after, and probably others too.  (There was a minor non-semantic code change in this case too.)

    Herm

**Comment by neilapwills** [comment]
Let me know if we can check in the modified variation file or just hold off until the other changes are available.  Will be on vacation next week will check in.  Cheers, Neil

**Comment by neilapwills** [comment]
noted that DocumentFiscalYearFocus is reported twice in the instance in DQC_0033.2.39
rules\xbrl.us\dqc\DQC_Testcases_v28\DQC_0033\DQC_0033.2\CASE_39\testco-20141231_39.xml

**Comment by campbellpryde** [comment]
The documentation will be updated to the following:
"Flag fail when one of the following DEI elements has a context end date that is different than the value entered for the context of DocumentPeriodEndDate.
DocumentType
AmendmentFlag
DocumentFiscalPeriodFocus
EntityRegistrantName
EntityCentralIndexKey
EntityCurrentReportingStatus
EntityVoluntaryFilers
CurrentFiscalYearEndDate
EntityFilerCategory
CurrentFiscalYearEndDate
EntityWellKnownSeasonedIssuer
DocumentFiscalYearFocus"

**Comment by neilapwills** [comment]
We can check in the test case variation file.

On Mon, Aug 31, 2015 at 12:17 PM, campbellpryde <notifications@github.com>
wrote:

> The documentation will be updated to the following:
> "Flag fail when one of the following DEI elements has a context end date
> that is different than the value entered for the context of
> DocumentPeriodEndDate.
> DocumentType
> AmendmentFlag
> DocumentFiscalPeriodFocus
> EntityRegistrantName
> EntityCentralIndexKey
> EntityCurrentReportingStatus
> EntityVoluntaryFilers
> CurrentFiscalYearEndDate
> EntityFilerCategory
> CurrentFiscalYearEndDate
> EntityWellKnownSeasonedIssuer
> DocumentFiscalYearFocus"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataQualityCommittee/dqc_us_rules/issues/5#issuecomment-136473186>
> .
>



-- 

___________________________________________

*Neil Wills*
Director of Software Development, XBRL Products
R.R. Donnelley & Sons Company

Desk: 425-378-3214

**Comment by susanyount-wf** [comment]
Documentation has been updated.
