### ISSUE TITLE
BusinessAcquisitionPurchasePriceAllocationAssetsAcquiredLiabilitiesAssumedNet

### ISSUE THREAD

**Issue by deantp** [DataQualityCommittee/dqc_us_rules#51]
For the historical rule checking

**Comment by campbellpryde** [comment]
This element represents the total purchase price of the acquired entity. This includes cash paid to equity interest holders of the acquired entity, fair value of debt and equity securities issued to equity holders of the acquired entity, and transaction costs paid to third parties to consummate the acquisition. If this was negative it would mean the entity paid the reporting entity to acquire the business.
