### ISSUE TITLE
IFRS 2021 support

### ISSUE THREAD

**Issue by jonathan-lord-compsci** [DataQualityCommittee/dqc_us_rules#560]
The SEC has started accepting IFRS 2021. I see v16 supports IFRS 2021. Please let me know if it will be added to earlier releases. Otherwise, could you please remind me of the timeline for v16's release?

**Comment by davidtauriello** [comment]
Hi @jonathan-lord-compsci - we're finalizing code and docs for a v15 release candidate that will go to DQC for approval next week. We anticipate this will have an IFRS 2021 ruleset.

**Comment by campbellpryde** [comment]
We have added the 2021 for V15 as well. This will be approved next week,
and will be up by next Friday.

Campbell Pryde

President and CEO

XBRL US Inc.


***@***.*** ***@***.***>*

*https://xbrl.us <https://xbrl.us>*

+ 1 (917) 582-6159 (Mobile)


[image: XBRL US]

The non-profit community <https://xbrl.us/xusmembers> improving U.S.
reporting through a free, open standard
<https://xbrl.us/home/learn/free-open-standards/>.
