### ISSUE TITLE
Bad exch schema reference in v16 IFRS 2021 ruleset

### ISSUE THREAD

**Issue by jonathan-lord-compsci** [DataQualityCommittee/dqc_us_rules#561]
The v16 IFRS 2021 ruleset references:

https://xbrl.sec.gov/exch/2021/exch-2021-01-31.xsd

But should in fact reference:

https://xbrl.sec.gov/exch/2021/exch-2021.xsd

**Comment by campbellpryde** [comment]
Thank you,

Good catch

Campbell Pryde

President and CEO

XBRL US Inc.


***@***.*** ***@***.***>*

*https://xbrl.us <https://xbrl.us>*

+ 1 (917) 582-6159 (Mobile)


[image: XBRL US]

The non-profit community <https://xbrl.us/xusmembers> improving U.S.
reporting through a free, open standard
<https://xbrl.us/home/learn/free-open-standards/>.
