### ISSUE TITLE
DEI 2021q4 support

### ISSUE THREAD

**Issue by jonathan-lord-compsci** [DataQualityCommittee/dqc_us_rules#616]
The SEC has started accepting DEI 2021q4. Please let me know when support will be added.

**Comment by sagesmith-wf** [comment]
Hey, @jonathan-lord-compsci I don't maintain this repo, but I think they have switched over to https://github.com/xbrlus/xule. Additionally I believe https://github.com/Arelle/Arelle is also supporting the rules

**Comment by davidtauriello** [comment]
Hi @jonathan-lord-compsci - sorry for the delay in responding and thanks, @sagesmith-wf for pinging this thread. 

The DQC has not yet developed rules for the enhancements in this DEI release, although that will not prevent the current approved release (v16) or latest public exposure (v17.0.0RC7) from working properly.

We're continuing to develop rules for Data Quality in this repository; the 'xule' cite in Sage's note is a reference to the underlying plugin that processes these rules - that code serves a number of projects, so a centralized 'master' is now maintained there, and fed into repositories as it is updated.
