### ISSUE TITLE
DQC 0004 This rule should have a tolerance of half a percent 

### ISSUE THREAD

**Issue by neilapwills** [DataQualityCommittee/dqc_us_rules#7]
Reviewing the compliance description we noted:

dqc_us_rules-master\dqc_us_rules-master\tests\test_suite\DQC_Testcases_2015-07-14\DQC_Testcases_v28\DQC_0004\variation.xml

Note "This rule should have a tolerance of half a percent "

 <description>Create a fail case when Assets is not equal to LiabilitiesAndStockholdersEquity with the same context. This rule should have a tolerance of half a percent of the value of Assets.If the difference is within this tolerance then the rule will not report.</description>

Is this implemented in the reference implementation?

dqc_us_rules-master\dqc_us_rules-master\src\dqc_us_0004.py

We did not see the half of percent defined under:
https://github.com/DataQualityCommittee/dqc_us_rules/blob/master/docs/DQC_US_0004/DQC_0004.md

**Comment by campbellpryde** [comment]
This should have said the following:
Create a fail case when Assets is not equal to LiabilitiesAndStockholdersEquity with the same context. This rule should take into account the tolerance of using different decimal values for the numbers being compared. If the difference is within this tolerance then the rule will not report.

This will be updated in the test suite.

**Comment by neilapwills** [comment]
Therefore whenfavc comparing the facts then no tolerance +\- is used after the fact values have been retrieved.

When you retrieve the fact values, and using the minimum decimals value between the facts to  be compared and using round half even for rounding.

**Comment by campbellpryde** [comment]
The rule as defined only allows the tolerance of the lowest decimal. Values
with a higher precision are rounded to the lowest decimal using round half
even.

Campbell Pryde

President and CEO

(917) 582-6159


1211 Avenue of the Americas, 19th Floor

New York, NY 10036-8775


*xbrl.us* <http://xbrl.us/> is the national consortium

for xbrl business reporting standards

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate

**Comment by hefischer** [comment]
Above-referenced rule tolerance now utilizes the minimum inferred decimals of asset and liabilities facts being compared.
