### ISSUE TITLE
DQC plugin not reporting fact label particles 

### ISSUE THREAD

**Issue by neilapwills** [DataQualityCommittee/dqc_us_rules#8]
Here is an attached screenshot:

![2015-08-26_19-39-52](https://cloud.githubusercontent.com/assets/13490426/9511321/51225de0-4c2a-11e5-85b5-6481943bef3a.png)

Ubuntu, Mac O/S's have this issue, I tried setting the Arelle language setting to conform that it was set to the en-US region.

[DQC.US.0004.16] ${fact1.label} with a value of ${fact1.value} is not equal to the total of ${fact2.label} with a value of ${fact2.value}.  These values should be equal. 
The properties of this ${fact1.name} fact are:
Period: ${fact1.period}
Dimensions: ${fact1.dimensions}
Unit: ${fact1.unit}
Rule version: ${ruleVersion} - ck0001532288-20150630.xml 100, 106

**Comment by hefischer** [comment]
Fixed, same as issue $6
