### ISSUE TITLE
ESEF Rule Set Map Points to Nonexistent 2023 Rule Set

### ISSUE THREAD

**Issue by austinmatherne-wk** [DataQualityCommittee/dqc_us_rules#800]
This was reported as an issue in the Arelle repo (Arelle/Arelle#1040).

The ESEF ruleset map [points to a 2023 ruleset zip](https://github.com/DataQualityCommittee/dqc_us_rules/blob/c73d5b67794316d5aef2f21e887b5033962c6c63/esefRulesetMap.json#L2) which does not exist.

**Comment by austinmatherne-wk** [comment]
Duplicate of #799

**Comment by davidtauriello** [comment]
@austinmatherne-wk - thanks; the latest XULE release (today) updates the ruleset map files for our plugin.
