### ISSUE TITLE
rulesetMap.json is missing 2024 IFRS

### ISSUE THREAD

**Issue by michaelchadfleming** [DataQualityCommittee/dqc_us_rules#848]
The file rulesetMap.json in master latest release is missing 2024 IFRS

https://github.com/DataQualityCommittee/dqc_us_rules/blob/53dc37f9c2d64a960fe91ac14b28f0b51a61a67d/rulesetMap.json

**Comment by davidtauriello** [comment]
Hi @michaelchadfleming - thanks for reporting this; it's fixed with [9822b7e](https://github.com/DataQualityCommittee/dqc_us_rules/commit/9822b7e21667ff41442721a213de6f0e9360425f) and v24.0.4 has been re-released with this change.
