### ISSUE TITLE
Windows 7 Arelle and DQC install guidelines?

### ISSUE THREAD

**Issue by DerekBurnham** [DataQualityCommittee/dqc_us_rules#9]
Are there any guidelines to properly installing Arelle and the dqc_us_rules package? I've tried to get the rules running through Arelle and adding the dqc_us_rules as a plugin and to date I've only gotten one test case to return a dqc result. Even then, it didn't populate the error labels as expected.

Thank you

**Comment by andrewperkins-wf** [comment]
@DerekBurnham We did an update recently that includes an import for the logging plugin, which should handle the error labels being populated properly.  Are there other issues you are seeing after that update?

**Comment by hefischer** [comment]
Fixed, appears to be same as #6, please re-open if not.
